replicaCount: 1

image:
  repository: ghcr.io/imtby/inenp-todo-demo
  tag: "1.0.0"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

# Environment variables
env:
  APP_TWO_URL: "http://app-two:80"

resources: {}
nodeSelector: {}
tolerations: []
affinity: []
