replicaCount: 1

image:
  repository: ghcr.io/imtby/inenp-todo-demo
  tag: "1.0.0"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 3000

resources: {}
nodeSelector: {}
tolerations: []
affinity: []
